### PR TITLE
Rust implementation

### PR DESCRIPTION
**Pull request by danipardo**

### CODE REVIEW

**Comment by emilybache** [comment]
Hi, Thanks for this! I don't know Rust and it would be a great addition to this repo. However, I had a look at the translation code and it's not quite how I want it. Tennis1 looks fine. Tennis2 doesn't look familiar, and you seem to have not translated Tennis3 at all. I am well aware that Tennis2 is rather horrible code and probably isn't that easy to translate. I wonder if it might be better to leave it out entirely in that case? How about Tennis3, is that also too hard to translate?

**Comment by danipardo** [comment]
Well, my aim wasn't really to translate from other languages, maybe I took Tennis1 as a base starting point. Then I just refactored Tennis1 in a more idomatic rust, which feels a bit more plain and linear. I didn't really know all other languages where refactoring in the same way TBH. I can do a rust translation if you want, it should be easy.

**Comment by emilybache** [comment]
This repo is meant to be a starting point for people who want to practice their refactoring skills. The three versions of Tennis present different refactoring challenges. I don't want you to include your solution, or your best guess at a Rust idiomatic version. I want a Rust translation of the three versions of Tennis. So if you don't want to translate the other two, that's fine, just please remove your own solution and only leave the translation of Tennis1. Perhaps someone else who knows Rust will come along and translate the other two.

**Comment by emilybache** [comment]
I should also mention I'm really glad you had a go at your own solution and thought about an idiomatic Rust solution! That's great, I hope you learnt something useful from that exercise. I just don't want to include the result in this repo.

**Comment by danipardo** [comment]
Oh, I see. Well, I've removed the refactoring I came up with.

**Comment by emilybache** [comment]
Thankyou, this looks great!

**Pull request merged**
