### PR TITLE
Java part : migration JDK 1.8 -> JDK 17, JUnit 4 -> JUnit5

### PR DESCRIPTION
**Pull request by SimonGirardSfeir**
Hello,

For the Java part of the Kata, I change the version of Java from 1.8 to 17.
Otherwise, I chose the version 5 of JUnit and I introduced the associated way of doing parameterised tests.

### CODE REVIEW

**Comment by codecop** [comment]
Could this be a separate folder "java-junit5" instead of a change? Sometimes older/different versions of testing frameworks have value for people still stuck with them.

**Comment by SimonGirardSfeir** [comment]
Ok, I can do this, but personally, I prefer to hava one unique folder per language. Otherwise, we can also create a folder for each version of Java/testing framework and maybe it will be too much.

**Comment by codecop** [comment]
I proposed it that way because it is that way with JS/Jest. Other repositories have it set up the way you describe it. I am undecided. @emilybache how would you like different testing frameworks for same language set up?

**Comment by emilybache** [comment]
For many of my exercises, writing the tests is a part of it, and you can practice test design techniques. For this exercise though, the whole focus is on refactoring. The tests are meant to just pass, be fast, and not get in the way of refactoring. So for this exercise I think it's unnecessary to have different folders per test framework.

**Comment by emilybache** [comment]
Thankyou for both offering your opinions and code, I really appreciate it.

**Pull request merged**
